---
# tasks file for aspects_apache22

- include: installPackages.yml
  tags:
  - aspects_apache22

- include: DebianMain.yml
  when:
    (ansible_distribution == "Ubuntu" and ansible_distribution_version == "12.04") or
    (ansible_distribution == "Debian" and ansible_distribution_major_version == "7") or
    (ansible_distribution == "Debian" and ansible_distribution_major_version == "6")
  tags:
  - aspects_apache22

- include: RedHatMain.yml
  when:
    (ansible_os_family == "RedHat" and ansible_distribution_major_version == "6")
  tags:
  - aspects_apache22