---
# tasks file for aspects_apache22

- include: installPackages.yml
  tags:
  - aspects_apache22

- include: DebianMain.yml
  when:
    (ansible_distribution == "Ubuntu" and ansible_distribution_version == "12.04") or
    (ansible_distribution == "Debian" and ansible_distribution_major_version == "7") or
    (ansible_distribution == "Debian" and ansible_distribution_major_version == "6")
  tags:
  - aspects_apache22

#- include: RedhatMain.yml
#  when:
#    (ansible_distribution == "CentOS" and ansible_distribution_version == "12.04") or
#    (ansible_distribution == "Debian" and ansible_distribution_major_version == "7") or
#    (ansible_distribution == "Debian" and ansible_distribution_major_version == "6")
#  tags:
#  - aspects_apache22